### PR TITLE
(GH-10) Add Debian 9 as additional option

### LINKED ISSUE #10: Add Debian 9 as additional option
We can switch to use `Debian 9` instead of `Ubuntu 16.04` as base.

Tried using `Ubuntu 18.04` but this gives some problems:

`Unable to locate package libicu55`

and after manually installing `libicu55`

```sh
1. Determining matching Azure Pipelines agent...
2. Downloading and installing Azure Pipelines agent...
3. Configuring Azure Pipelines agent...

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required
 for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
   /azp/agent/externals/tee/license.html


>> Connect:
Connecting to server ...
No usable version of the libssl was found
./config.sh: line 86:    68 Aborted                 ./bin/Agent.Listener configure "$@"
```

### PR DESCRIPTION
**Pull request by jokay**
Add `debian:stretch-slim` as additional option.

Fixes #10.

### CODE REVIEW

**Comment by pascalberger** [comment]
I prefer to first have versioning / tagging fixed (#12) before we switch / enhance to more distros

**Comment by jokay** [comment]
Why not dropping support for the Ubuntu base and go for Debian, this will remove some unnecessary dependencies?

**Comment by pascalberger** [comment]
As said, we need to first define and switch to a proper versioning / tagging as described in #12

**Comment by jokay** [comment]
@pascalberger ready for a second review.

**Pull request closed without merging**
